apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: pod1-rs
spec:
  replicas: 3
  template:
    metadata:
      name: pod1
      labels:
        app: pod1
    spec:
      containers:
        - name: container-pod1
          image: nginx:latest
          ports:
            - containerPort: 80
  selector:
    matchLabels:
      app: pod1
